# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/yorbe/Documents/School/3_Basis_Digitale_Elektronica_2/Opdracht3/RandomPixels/RandomPixels.srcs/sources_1/ip/VideoMemory/VideoMemory.xci
# IP: The module: 'VideoMemory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yorbe/Documents/School/3_Basis_Digitale_Elektronica_2/Opdracht3/RandomPixels/RandomPixels.srcs/sources_1/ip/VideoMemory/VideoMemory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VideoMemory'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/yorbe/Documents/School/3_Basis_Digitale_Elektronica_2/Opdracht3/RandomPixels/RandomPixels.srcs/sources_1/ip/VideoMemory/VideoMemory.xci
# IP: The module: 'VideoMemory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yorbe/Documents/School/3_Basis_Digitale_Elektronica_2/Opdracht3/RandomPixels/RandomPixels.srcs/sources_1/ip/VideoMemory/VideoMemory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VideoMemory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
