# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/imports/ConfigVoltages.xdc

# XDC: imports/imports/Nexys-4-DDR-Master.xdc

# IP: ip/ClockingWizard/ClockingWizard.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ClockingWizard || ORIG_REF_NAME==ClockingWizard} -quiet] -quiet
